/*
 * The contents of this file are subject to the terms of the Common Development and
 * Distribution License (the License). You may not use this file except in compliance with the
 * License.
 *
 * You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
 * specific language governing permission and limitations under the License.
 *
 * When distributing Covered Software, include this CDDL Header Notice in each file and include
 * the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
 * Header, with the fields enclosed by brackets [] replaced by your own identifying
 * information: "Portions Copyrighted [year] [name of copyright owner]".
 *
 * Copyright 2014 ForgeRock AS. All rights reserved.
 */

package org.forgerock.openam.sts.token.validator.wss.disp;

import org.forgerock.json.fluent.JsonValue;
import org.forgerock.openam.sts.TokenMarshalException;

/**
 * Defines the interface necessary to parse the json callback generated by the RestAuthX509CallbackHandler, which
 * is encapsulated by the overall callback structure, and set the X509Certificate state necessary to satisfy this
 * callback.
 *
 */
public interface RestX509CallbackParser {
    /**
     * Will return a JsonValue encapsulating the base64 encoded representation of the X509Certificate in the callback
     * structure returned by the RestAuthX509CallbackHandler.
     * @param initialCallback The callback returned by the first call to the rest authN context targeting the Cert authN module.
     * @param base64EncodedCertificate The client certificate, validated by two-way-tls, which will be posted to the Cert authN module,
     *                                 in base64 format.
     * @return the JsonValue corresponding to the updated callback containing the base64 encoded representation of the X509Certificate.
     * @throws TokenMarshalException In case some element of the json parsing and certificate encoding operations fail.
     */
    JsonValue updateCallbackWithCertificateState(String initialCallback, String base64EncodedCertificate) throws TokenMarshalException;
}
